param(
    [Parameter(Mandatory = $true)]
    [string]$ApkPath,

    [string]$OutputDirectory = "assets/helper",

    [string]$AaptPath,

    [string]$ApkSignerPath
)

$ErrorActionPreference = "Stop"

function Resolve-AndroidTool {
    param(
        [string]$ExplicitPath,
        [string]$ToolName
    )

    if ($ExplicitPath) {
        if (-not (Test-Path -LiteralPath $ExplicitPath)) {
            throw "$ToolName not found at '$ExplicitPath'."
        }
        return (Resolve-Path -LiteralPath $ExplicitPath).Path
    }

    $sdkRoot = $env:ANDROID_HOME
    if (-not $sdkRoot) {
        $sdkRoot = $env:ANDROID_SDK_ROOT
    }

    if ($sdkRoot) {
        $toolFile = if ($IsWindows) { "$ToolName.exe" } else { $ToolName }
        $buildTools = Join-Path $sdkRoot "build-tools"
        if (Test-Path -LiteralPath $buildTools) {
            $candidate = Get-ChildItem -LiteralPath $buildTools -Directory |
                Sort-Object Name -Descending |
                ForEach-Object { Join-Path $_.FullName $toolFile } |
                Where-Object { Test-Path -LiteralPath $_ } |
                Select-Object -First 1

            if ($candidate) {
                return $candidate
            }
        }
    }

    $command = Get-Command $ToolName -ErrorAction SilentlyContinue
    if ($command) {
        return $command.Source
    }

    throw "$ToolName was not found. Set ANDROID_HOME or pass -${ToolName}Path explicitly."
}

function Invoke-Checked {
    param(
        [string]$FilePath,
        [string[]]$Arguments
    )

    $output = & $FilePath @Arguments 2>&1
    if ($LASTEXITCODE -ne 0) {
        $text = ($output | Out-String).Trim()
        throw "'$FilePath $($Arguments -join ' ')' failed with exit code $LASTEXITCODE.`n$text"
    }
    return ($output | Out-String).Trim()
}

$resolvedApk = Resolve-Path -LiteralPath $ApkPath -ErrorAction Stop
$aapt = Resolve-AndroidTool -ExplicitPath $AaptPath -ToolName "aapt"
$apksigner = Resolve-AndroidTool -ExplicitPath $ApkSignerPath -ToolName "apksigner"

$badging = Invoke-Checked -FilePath $aapt -Arguments @("dump", "badging", $resolvedApk.Path)
$signature = Invoke-Checked -FilePath $apksigner -Arguments @("verify", "--print-certs", $resolvedApk.Path)

$requiredPatterns = @(
    "package: name='com.sysadmindoc.phonefork.helper'",
    "sdkVersion:'30'",
    "targetSdkVersion:'36'"
)

foreach ($pattern in $requiredPatterns) {
    if ($badging -notlike "*$pattern*") {
        throw "Helper APK metadata check failed. Missing pattern: $pattern"
    }
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$outputRoot = if ([System.IO.Path]::IsPathRooted($OutputDirectory)) {
    $OutputDirectory
} else {
    Join-Path $repoRoot $OutputDirectory
}

New-Item -ItemType Directory -Force -Path $outputRoot | Out-Null

$stagedApk = Join-Path $outputRoot "PhoneForkHelper.apk"
$metadataPath = Join-Path $outputRoot "PhoneForkHelper.apk.metadata.txt"
$hashPath = Join-Path $outputRoot "PhoneForkHelper.apk.sha256"

Copy-Item -LiteralPath $resolvedApk.Path -Destination $stagedApk -Force
@(
    "# PhoneFork helper APK metadata"
    "# Generated by scripts/Stage-HelperApk.ps1 on $(Get-Date -Format o)"
    ""
    "[aapt dump badging]"
    $badging
    ""
    "[apksigner verify --print-certs]"
    $signature
) | Set-Content -LiteralPath $metadataPath -Encoding UTF8

$hash = Get-FileHash -Algorithm SHA256 -LiteralPath $stagedApk
"$($hash.Hash.ToLowerInvariant())  PhoneForkHelper.apk" | Set-Content -LiteralPath $hashPath -Encoding ASCII

Write-Host "Staged verified helper APK: $stagedApk"
Write-Host "Metadata: $metadataPath"
Write-Host "SHA-256: $hashPath"
